# Generated by Django 5.1.5 on 2025-05-11 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fromDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
