# Generated by Django 5.1.5 on 2025-05-11 09:18

import milk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0002_order_fromdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='endDate',
            field=models.DateField(default=milk.models.default_to_date),
        ),
    ]
