# Generated by Django 5.1.5 on 2025-05-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0003_order_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverytime',
            field=models.CharField(default='morning', max_length=50),
        ),
    ]
