# Generated by Django 5.1.5 on 2025-05-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0004_order_deliverytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliverytime',
            field=models.CharField(default='enter the shift', max_length=50),
        ),
    ]
